export const SET_USERS = "SET_USERS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_PAGE_SIZE = "SET_PAGE_SIZE";
export const SET_TOTAL_COUNT_ELEMENTS = "SET_TOTAL_COUNT_ELEMENTS";
export const SET_ORDER_TYPE = "SET_ORDER_TYPE";
export const SET_ORDER_FIELDS = "SET_ORDER_FIELDS";
export const SET_SEARCH_WORD = "SET_SEARCH_WORD";
